# -*- coding: utf-8 -*-
"""Exerxise1-a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wi8Cvyd4TU2YmgtbQodrtZMKEvzUNo19
"""

#student registration

name=input("Enter students name: ")
roll_no=input("Enter roll_no: ")
dep=input("Enter department: ")
print("Name:",name)
print("Roll_No:",roll_no)
print("Department:",dep)